### PR TITLE
Encryption Feature

### PR DESCRIPTION
**Pull request by onizenso**
Creates an encrypted project archive for current project. Uses the `cryptography.Fernet` module to encrypt an archive (zip/tar.bz2) as a bytestream. The symmetric key for `Fernet` is derived using `scrypt` with a user-supplied password and 16-byte salt pulled from `/dev/urandom`. 

`Fernet` uses `AES-128-CBC` with `HMAC-SHA256` for message (archive) authentication. An alternative scheme using `AES-256-GCM` is under development to provide a stronger symmetric encryption cypher. `AES-256-GCM` is in the `cryptography.hazmat` modules, making it imperative to know exactly what is going on before developing a working cryptosystem (I definitely need to do more research before attempting :)

### CODE REVIEW

**Comment by roglew** [comment]
Awesome! Just glancing over the code this looks pretty good. My schedule is pretty hectic over the next few days but I'll make sure to look this over/merge it as soon as I can.

**Comment by roglew** [comment]
Alright, I looked through and noticed a few things.

- The Session.encrypt() Session.decrypt() functions look a little weird. Is there a reason that these need to be async? decrypt() doesn't generate any deferreds (and there's a yield True which is a bit weird, you might have meant defer.returnValue) and Crypto.encrypt_project() doesn't return a deferred so there's no reason to yield it from Session.encrypt(). You may want to just remove the defer.inlineCallbacks decorator and just treat them as normal functions.
- You can probably get rid of config.crypt_success and instead have decrypt() return whether it succeeded, or even better use a try/except block and have the program print an error, maybe do some cleanup, and quit if an exception is raised. Right now the program also crashes when creating a new project file because config.crypt_success doesn't get set to true and the program doesn't quit if it's false.
- Is there an alternative to keeping the project salt with the project file? It would be much easier to only have to deal with one file rather than 2 if it's possible. Since we're not worrying about making the project file a standard format it might be possible to just make the first/last 16 bytes of the file be the salt rather than storing the salt in a separate file.
- Consider using [getpass](https://docs.python.org/2/library/getpass.html) for password entry instead of raw_input
- Do some checks for if files/directories already exist append some random numbers until the filename doesn't exist. (For example `crypt/` and `project.archive`).

This seems pretty good so far though, thanks again for putting in the work!

**Comment by onizenso** [comment]
Roglew, I agree with your points, on most of them wasn't sure how they would fit in with the rest of the core project.

* Both `Session.encrypt()` and `Session.decrypt()` don't need to be async. Just made them async because I saw most of the methods for Session were async. Didn't know if I needed to do that to make them play nice with Twisted. I'll change them to regular functions, and see if that fixes some of the issues.

* I'll try to work out something to append the salt to the end of the encrypted archive, then strip that when decrypting. Slightly more complicated than the current scheme, but agree it would be worth it to cut down on number of files (especially just for a 16-byte string).

* `crypt_success` was just to make `Session.decrypt` play nice with the rest of the startup when the user enters an incorrect password. I can most likely remove it without consequence when I change `Session.decrypt` and `Session.encrypt` to regular functions. I'll see if removing the conditional and `crypt_success` removes the crashes.

* Was thinking of using `getpass`, just wasn't sure if adding another dependency was worth it. If you're cool with it I'll add it.

* `crypt/` and `project.archive` should only exist during a live crypto session, or if pappy dies in the middle of a project. So right now, I check to see if `crypt/` exists, and resume the session to recover where the project left off. This is an attempt to salvage the project when an unexpected crash happens (e.g. computer crashes during middle of a session). If I appended random strings that would just start a new session, leaving the old crypto project files in the clear.

Hopefully should have the fixes done soon, and thanks for the feedback on the pull request :)

**Comment by roglew** [comment]
Great, thanks! I'll keep an eye out for the update.

**Comment by onizenso** [comment]
@roglew just updated the project with the changes you asked for, with a couple exceptions. Haha took me a while to figure out how to get pappy to close cleanly without clobbering Twisted threads, but I think I got it now. "Threads are hard..." Let me know what you think of the updates, and if there are any more changes you would like to see.

I left out the name collision with `crypt/` because the only time there would be a collision is if there was a successful decryption, the `crypt_file` didn't get deleted, and pappy exits uncleanly (e.g. from unexpected OS shutdown). 

However, `crypt_file` gets deleted on every succesful decryption. If you still want me to add the random working directory naming, I can, but I don't see a need for it atm.

**Comment by roglew** [comment]
Great! It looks like it works pretty well. I'll merge it and add some docs to the README on the next release. Thank you so much for implementing this, it's really cool!

**Pull request merged**
